version: '3.9'

services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
