// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"app/internal/handler"
	"app/internal/repository"
	"app/internal/usecase"
	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Wire(db *gorm.DB, WebAuthn *webauthn.WebAuthn) *handler.Handlers {
	sessionRepository := repository.NewSessionRepository()
	userRepository := repository.NewUserRepository()
	registerUsecase := usecase.NewRegisterUsecase(sessionRepository, userRepository, WebAuthn)
	loginUsecase := usecase.NewLoginUsecase(sessionRepository, userRepository, WebAuthn)
	handlers := handler.NewHandlers(registerUsecase, loginUsecase)
	return handlers
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewSessionRepository, repository.NewUserRepository)

var usecaseSet = wire.NewSet(usecase.NewRegisterUsecase, usecase.NewLoginUsecase)

var handlerSet = wire.NewSet(handler.NewHandlers)
