// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"app/internal/handler"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Wire(db *gorm.DB) *handler.Handlers {
	handlers := handler.NewHandlers()
	return handlers
}

// wire.go:

// プロバイダーセットの定義
var handlerSet = wire.NewSet(handler.NewHandlers)
