openapi: 3.0.0
info:
    title: "WebAuthn API"
    description: "This is a WebAuthn API"
    version: "1.0.0"
paths:
    /passkey/register-challenge:
        post:
            operationId: register-challenge-passkey
            summary: "Register a new passkey"
            tags:
                - WebAuthn
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/RegisterChallengePasskeyRequest" 
            responses:
                "200":
                    description: "Challenge generated"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/RegisterChallengePasskeyResponse"
                    headers:
                        Set-Cookie:
                            description: Set-Cookie
                            schema:
                                type: string
    /passkey/login-challenge:
        post:
            operationId: login-challenge-passkey
            summary: "Generate a login challenge"
            tags:
                - WebAuthn
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginChallengePasskeyResponse'
                    headers:
                        Set-Cookie:
                            description: Set-Cookie
                            schema:
                                type: string
    /passkey/register:
        post:
            operationId: register-passkey
            summary: "Register a passkey"
            tags:
                - WebAuthn
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterPasskeyRequest'
            responses:
                '201':
                    description: Created
    /passkey/login:
        post:
            operationId: login-passkey
            summary: "Login with a passkey"
            tags:
                - WebAuthn
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginPasskeyRequest'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginPasskeyResponse'

components:
  schemas:
    RegisterChallengePasskeyRequest:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
        - email
    RegisterChallengePasskeyResponse:
      type: object
      description: Initialize Attestation Response
    LoginChallengePasskeyResponse:
      type: object
      description: Initialize Assertion Response
    RegisterPasskeyRequest:
      type: object
      description: Finalize Attestation Request
    LoginPasskeyRequest:
      type: object
      description: Finalize Assertion Request
    LoginPasskeyResponse:
      type: object
      description: Finalize Assertion Response
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id
security:
  - cookieAuth: []
